### ISSUE TITLE
Search tool: multi-word and hyphen-separated word glossary entires not matching

### ISSUE THREAD

**Issue by coderintherye** [kiva/viva_glossary_tool#11]
> I took a few minutes to click around this morning and experimented with the glossary tool search. I tried typing in "sari" with the Philippines selected as the country, and the prompt was to click if I wanted to see the entry for "suri":

> When I went back to the Colibri glossary, I checked that the correct country was selected and noticed that this entry has two terms entered. I also tried entering a term from Zimbabwe with two entries: "roadrunner chickens or road runner chickens", and it also yielded no results. Is this the expected outcome for now?

**Comment by coderintherye** [comment]
![screen shot 2018-07-27 at 10 38 52 am](https://user-images.githubusercontent.com/313805/43347875-1bd1ec94-91ac-11e8-8bf7-e0201e0a213e.png)

**Comment by kevinzwang** [comment]
"suri" and "roadrunner chickens" both work when you have Philippines and Zimbabwe selected, respectively. Should I make an option to search all of the countries?

**Comment by coderintherye** [comment]
@kevinzwang Oh I see, for sari, it is just a bit of confusion in the UI since the meaning is "see entry for suri" it makes it seem as if it is not picking it up. Im not sure if we want to make anything in the UI for it to be clearer, probably not, but I see why they got confused.

That said, for roadrunner chickens, I can't see to get it to come up when typing it in for Zimbabwe, is it possible this version of the extension from the chrome store maybe is different than one you are testing against and perhaps has an issue?

**Comment by kevinzwang** [comment]
I tested the chrome extension from the web store and it works for me. Make sure to log into colibri and then click reload extension.

**Comment by coderintherye** [comment]
@kevinzwang Ahh I see, maybe similar confusion they had to what I had, I thought merely from typing "roadrunner" it would come up, however it only comes up upon the full "roadrunner chickens"

**Comment by kevinzwang** [comment]
I'm not sure what the solution to that would be. Should I accept queries that are only part of the term? Alternatively, there could be search suggestions while searching, which would take some more time for me to make.

**Comment by coderintherye** [comment]
@kevinzwang though with "sari" I suppose also the issue is we first key off of the generic "sari" with no country attached glossary entry, but we don't bring up "sari-sari", even if typed that way and Philippines selected. I didn't step through the code, but is it possible the first generic entry is overriding the 2nd country-specific entry? Or is something else afoot in preventing us from getting sari-sari ?

**Comment by coderintherye** [comment]
@kevinzwang search suggestions are definitely a deeper dive , I could share some levenshtein distance javascript code with you for it, but I don't think it's likely worth it. That said, could you split terms based on spaces so that even if only searching for the first word in a multi-word term it will still come up? Meaning "roadrunner" will come up with "roadrunner chickens..." I imagine that would be relatively straight-forward to implement?

**Comment by kevinzwang** [comment]
Yes, that can work. As for sari-sari, it's because the term on ForumBee is "sari-sari, sari2x", which the regex does not split. I'll also fix that.

**Comment by kevinzwang** [comment]
@coderintherye One problem. Some terms have common first words, for example, cacao bean and cacao tree. What should I do in that case?

**Comment by coderintherye** [comment]
@kevinzwang is it possible to match based on the first word, but if the user keeps typing, then we pull up the more accurate match? Example: they type cacao, you pull up cacao bean, but if they fully type out cacao tree, then we pull that up ?

**Comment by kevinzwang** [comment]
It is possible, I just think it's not a nice solution because whichever definition is shown is basically random order.

**Comment by coderintherye** [comment]
@kevinzwang that's true, let's bring it back to the stakeholders to see what they think would be best
